context('2:Layout', () => {
    context('0: Basic', () => {
        test('3: Show/Hide Panels', () => {
            bela
                .ready('/w2ui/demos/#/layout/3')
                .begin('Check panels')
                    .get('#layout_layout_panel_top')
                    .should('be.visible')
                    .get('#layout_layout_panel_left')
                    .should('be.visible')
                .end()
                .begin('Hide top and left panels')
                    .get('button:contains(Top)').click()
                    .wait('#layout_layout_panel_top', 'to.be.hidden')
                    .get('button:contains(Left)').click()
                    .wait('#layout_layout_panel_left', 'to.be.hidden')
                .end()
                .begin('Show preview and right panels')
                    .get('button:contains(Preview)').click()
                    .wait('#layout_layout_panel_preview', 'to.be.visible')
                    .get('button:contains(Right)').click()
                    .wait('#layout_layout_panel_right', 'to.be.visible')
                .end()
        })
    })
})