context('1: Combo', () => {
    context('1: Basic', () => {
        test('2: Grid & Edit', () => {
            bela
                .ready('/w2ui/demos/#/combo/2')
                .begin('Check form')
                    .grid('grid')
                    .select(0)
                        .get('.w2ui-form #fname')
                        .should('have.value', 'John')
                        .get('.w2ui-form #lname')
                        .should('have.value', 'Doe')
                    .grid('grid')
                    .select(1)
                        .get('.w2ui-form #fname')
                        .should('have.value', 'Stuart')
                        .get('.w2ui-form #lname')
                        .should('have.value', 'Motzart')
                .end()
                .begin('Delete rest of records')
                    .grid('grid')
                    .select({ all: true })
                    .click(0, { metaKey: true })
                    .click(1, { metaKey: true })
                    .click('Delete', { confirm: 'Delete' })
                .end()
        })
    })
})