context('1: Combo', () => {
    context('1: Basic', () => {
        test('6: Tabs With Content', () => {
            bela
                .ready('/w2ui/demos/#/combo/6')
                .begin('Check tabs')
                    .get('#tab1')
                    .should('be.visible')
                    .get('#tab2')
                    .should('be.hidden')
                    .get('#tab3')
                    .should('be.hidden')
                    .get('#tabs_tabs_tab_tab2')
                    .should('contain.text', 'Tab 2')
                    .click()
                    .get('#tab2')
                    .should('be.visible')
                    .get('#tabs_tabs_tab_tab3')
                    .should('contain.text', 'Tab 3')
                    .click()
                    .get('#tab1')
                    .should('be.hidden')
                    .get('#tab2')
                    .should('be.hidden')
                    .get('#tab3')
                    .should('be.visible')
                .end()
        })
    })
})