context('3:Grid', () => {
    context('0: Basic', () => {
        test('1: Grid Elements', () => {
            bela
                .ready('/w2ui/demos/#/grid/3')
                .grid('grid')
                .should('have.records')
                .begin('Header')
                    .get('#grid_grid_header')
                    .should('be.visible')
                    .get('button:contains(Header)')
                    .click()
                    .get('#grid_grid_header')
                    .should('be.hidden')
                .end()
                .begin('Toolbar')
                    .get('#grid_grid_toolbar')
                    .should('be.visible')
                    .get('button:contains(Toolbar)')
                    .click()
                    .get('#grid_grid_toolbar')
                    .should('be.hidden')
                .end()
                .begin('Column Headers')
                    .get('#grid_grid_column_0')
                    .should('be.visible')
                    .get('button:contains(Column Headers)')
                    .click()
                    .should('not.exist', '#grid_grid_column_0')
                .end()
                .begin('Footer')
                    .get('#grid_grid_footer')
                    .should('be.visible')
                    .get('button:contains(Footer)')
                    .click()
                    .get('#grid_grid_footer')
                    .should('be.hidden')
                .end()
                .begin('Line Numbers')
                    .get('#grid_grid_cell_0_number')
                    .should('be.visible')
                    .get('button:contains(Line Numbers)')
                    .click()
                    .should('not.exist', '#grid_grid_cell_0_number')
                .end()
                .begin('Select Column')
                    .should('not.exist', '#grid_grid_cell_0_select')
                    .get('button:contains(Select Column)')
                    .click()
                    .get('#grid_grid_cell_0_select')
                    .should('be.visible')
                .end()
                .begin('Expand Column')
                    .should('not.exist', '#grid_grid_cell_0_expand')
                    .get('button:contains(Expand Column)')
                    .click()
                    .get('#grid_grid_cell_0_expand')
                    .should('be.visible')
                .end()
                .begin('Order Column')
                    .should('not.exist', '#grid_grid_cell_0_order')
                    .get('button:contains(Order Column)')
                    .click()
                    .get('#grid_grid_cell_0_order')
                    .should('be.visible')
                .end()
        })
    })
})