context('4:Toolbar', () => {
    context('1: 1.5+', () => {
        test('7: Color Buttons', () => {
            bela
                .ready('/w2ui/demos/#/toolbar/7')
                .get('#toolbar .w2ui-tb-button')
                .should('have.length', 2)
                .begin('Color button')
                    .get('#tb_toolbar_item_item1')
                    .click()
                    .wait(20)
                    .get('#w2ui-overlay .w2ui-color')
                    .should('have.length', 96)
                    .get('#w2ui-overlay .w2ui-color:eq(12)')
                    .click()
                    .get('#tb_toolbar_item_item1 .w2ui-tb-color-box')
                    .should('have.css', { 'background-color': 'rgb(255, 1, 27)' })
                .end()
                .begin('Text Color button')
                    .get('#tb_toolbar_item_item3')
                    .click()
                    .wait(20)
                    .get('#w2ui-overlay .w2ui-color')
                    .should('have.length', 96)
                    .get('#w2ui-overlay .w2ui-color:eq(12)')
                    .click()
                    .get('#tb_toolbar_item_item3 .w2ui-tb-text > span')
                    .should('have.css', { 'color': 'rgb(255, 1, 27)' })
                .end()
        })
    })
})